sudo: required
services:
  - docker
    
before_install:
  - docker build -t reddyatsg/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true reddyatsg/docker-react npm test -- --coverage 